travis:
  secure:
    BINSTAR_TOKEN: thfPHwpvZ7gLWr0ZBfFhsOnk9sykuEp+HAhiNj5j2CxVaMVqe3SJXI6KNu5y3QqusSdXZ3lywuJ1aGF8o2VBlbzcxqv5OKmzclPrpB4oSw4NS4MJ07Cl9Y5QMUKgIa3gYACnitjJTgqWUZCh5oYvhPUK0U3zq/hUNwSsUFIcYbHdX0fGSQHnnIJNWsjYAUx5UaqM2YRpIwGWx/L8PyMtdl2BiouwKmHgmIngtLPQIEj4WgJhpB1KzLn/ODSbaTfFMRaHsuI3YKgvQ4WlhKao6c1H0xTzXf2ccRrgmuBKnkW/OGI5bjGWQU4Ii6CJ7fKY5Nwv9lGAwTNRg9GzRqSoROQmeOIopw2T/gCsgCAUULxWpB9FZHnM+atC0V3457RgOy1z6rQ5fWo48RsuIwWYR757aOVF5/AGgUbymfOActVKxCQfJPpgKaAd2rSLPZWuaBENR1VwUr5F45/ThrBDPgeVvrBQ2XjvI4vpyVR/+imXRwhEZgAhwx3ZiAntXpyrx6ax00emm/QKrZhUTHvJjqJBGgf3GQphr0HDWobfn/f+eZ1W2ZaTft+pkzwO9Ern9GIHiGyqgMRyNkofJHzU+x8MPtbZ/Qznj1hvE12tTUL0z3w7VLY1X46wM1OZRd/tvXFgD66BHk8diQPsUMv/WatrLl9zt2XuTEVyUoMQsH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
