travis:
  secure:
    BINSTAR_TOKEN: v5O+bbnm/Z7PhJqkJFUkm0ynF40Tzlh2F873LVqAYd3haAzePOrI/Vo30l+KEz8Fiwg+9VEZwIinPDAX0Qk34TFIqtrybev8lCsM/7lAA3HGvPD+E7D6LosxP3jCuOYnNf0P5nRM03fBPj5s1OQ2n90Jc4UjFhOW5cvhuynCb7JY+Z7aY5nj7uocXZJOQRDdo3LjxG1UJHsipaKSuQBrF+H+PvWo6U1AAUrNL4kpQOcgGy2PG/h9Mt1W13nITf0e3pNVkT+EA7dxdxQF/xdLf27NnW9jLyfstkKic3R+/x7z6qC671EeazyhbQ0DDR0blXA8YYmxldgOA91sDkQwb3T2/f30jSOxKsKyljXUGKkq50IWC8TzBwqak1F+AB8YEjmKAo4BS2B4k1Z8wOKa2RO/2xOkGi8Khz44NyCJ33111rsMtd/j9GsD5CKeFykaZZmYzOAlhhJ6Vi97ZZVSqIAWEqyZI0iuD+D/HmJlSUQ4u6fQMlDJTxc4FIGSk+hkheEau3e1CftZCjD1YESQxW4dM0ghahEakrC+YeRFoALLcvOrBxPj3POwfhtDiRVGIrz/ou7kM8Dx1sPFF3VyszeBnPJOxKaE9VuNgkWmFR/r2EwnEzVJdT0fO6M7lwJeNRe4317IkNl1YXO+7UI7olz+hVALsaYG3m3ly8Peoao=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
